export const getAIResponse = async (question) => {
    // In a real application, you would make an API call to the Gemini AI here
    // For this example, we'll return a mock response
    await new Promise((resolve) => setTimeout(resolve, 1000)) // Simulate API delay
    return `Here's a mock response to your question: "${question}". This response is generated by an AI model and may not be entirely accurate or complete. Always verify important information from reliable sources.`
  }
  
  